### ISSUE TITLE
Build fails due to git://git.osmocom.org/rtl-sdr.git not connecting

### ISSUE THREAD

**Issue by jrmacias** [bademux/rtl_433toMQTT#1]
Hi,
When trying to build the image, I've got the error:

```
Cloning into 'rtl-sdr'...
fatal: unable to connect to git.osmocom.org:
git.osmocom.org[0: -----]: errno=Operation timed out
git.osmocom.org[1: ------]: errno=Address not available

```
This is probably due to changes in the upstream repository, and easily overcome by changing connection protocol to https:

` git clone https://github.com/osmocom/rtl-sdr.git`

Kind regards.

**Comment by bademux** [comment]
Thanks for reporting, don;t know what it was. 
build  from 07.03 is OK https://travis-ci.org/github/bademux/rtl_433toMQTT/builds/659514146
