### ISSUE TITLE
Fails to start with new image as of 3/22/21

### ISSUE THREAD

**Issue by dfiore1230** [bademux/rtl_433toMQTT#6]
Watchtower did its job and updated overnight, however the new image fails to start. 

Docker Run
`  docker run -d \
    --read-only \
    --restart unless-stopped \
    --name "rtl433" \
    --device=/dev/bus/usb/001/004 \
    -e RTL_OPTS="-f 433920000 -F mqtt://172.16.42.134,retain=1,events=homeassistant/sensor/honeywell -M utc" \
  bademux/rtl_433tomqtt:latest`

Logs
`
Registered 145 out of 175 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 ],
Publishing events info to MQTT topic "homeassistant/sensor/honeywell".,
Trying conf file at "/etc/rtl_433/rtl_433.conf"...,
Publishing MQTT data to 172.16.42.134 port 1883,
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...,
Trying conf file at "/home/user/.config/rtl_433/rtl_433.conf"...,
Trying conf file at "rtl_433.conf"...,
Use -h for usage help and see https://triq.org/ for documentation.,
rtl_433 version unknown inputs file rtl_tcp`

Switching back to the old image fires right up.

I can troubleshoot further, but not exactly sure what changed so not sure where to look

**Comment by bademux** [comment]
Woow, someone using it :) Thanks!
Let me check it
changelog:
- rtl_433 was updated to 20.11
- migrating to github actions CI
- I also migrate to autotools 

Autotool reverted back to cmake: please try v0.2.1 (baking right now https://github.com/bademux/rtl_433toMQTT/actions/runs/680192546 )

**Comment by dfiore1230** [comment]
@bademux cool thanks. Ya i trap all of my old home alarm rf signals and pipe it out via mqtt, grabbing that up in home assistant to use as sensors. They are mainly door/window, but i have also added weather sensors from accurite with temp/humidity etc. Works really well for alerting and automations. 

once the build finishes ill give it a go. I can compare direct as i have 2 USB SDR's one each for 345 and 433.

Dave

**Comment by bademux** [comment]
sorry about that, please use @sha256 tagging, like ``` docker image pull ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2 ```
This way you can assert specific docker container.

**Comment by dfiore1230** [comment]
0.2.1 fires right up and runs as expected. deployed it on both of my containers and will keep an eye on them.

**Comment by bademux** [comment]
Great! Please comment here if something will go wrong, I will reopen the issue
