### ISSUE TITLE
Assertion failed: clock_gettime(1, tp) == 0 (libusbi.h: usbi_get_monotonic_time: 497)

### ISSUE THREAD

**Issue by koenvervloesem** [bademux/rtl_433toMQTT#7]
The newest Docker image doesn't start on 32-bit Raspberry Pi OS Buster (armv7l). There's an issue with Alpine 3.13 containers on this distro. See https://github.com/hertzg/rtl_433_docker/issues/3. Changing to the `hertzg/rtl_433:alpine-3.12-latest` container image works. Maybe you can also add an Alpine 3.12 based image until the issue has been fixed.

**Comment by bademux** [comment]
@koenvervloesem Thanks for reporting.

There is trade off between complexity and configurability. For this project I choose simplicity - there is  no way to configure image image per platform for automatic builds. Downgrading all images isn't the solution too :(

Maybe you have an information about the issue so I can track the issue? Is it reported to alpine?

**Comment by bademux** [comment]
And what do you  think about 
https://github.com/hertzg/rtl_433_docker/issues/4#issuecomment-806128238
According to @mpuff it is Raspbian problem:
 
> you need to install this for the new alpine docker image:
> 
> wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
> sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb
> 
> than it should work ;)
> I had this problem also on another alpine docker image. Than i have updated this container, same error, after the installation of this libusb was the container starting again.
> I found this info in another chat

**Comment by mpuff** [comment]
For me it is working, you can try it on a test installation and you will see 😉
![github_docker](https://user-images.githubusercontent.com/13885599/118410202-8ea94000-b68e-11eb-9e3c-80fda1c88f6a.png)

**Comment by koenvervloesem** [comment]
Interesting, so actually someone should prod the Raspberry Pi OS developers to upgrade their libseccomp2 package.

At LinuxServer.io they have an entry in their FAQ with a good overview of solutions: https://docs.linuxserver.io/faq

**Comment by bademux** [comment]
resolved?
